spring:
  application:
    name: hobby-stock-api
  
  datasource:
    url: jdbc:postgresql://localhost:5432/hobbystock
    username: hobbystock
    password: hobbystock
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

server:
  port: 8080
  servlet:
    context-path: /

graphql:
  servlet:
    mapping: /graphql
    enabled: true
    cors:
      allowed-origins: http://localhost:3000
      allowed-methods: GET, POST, OPTIONS
      allowed-headers: "*"

graphiql:
  enabled: true
  mapping: /graphiql
  endpoint: /graphql

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized

logging:
  level:
    com.hobbystock: DEBUG
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
